// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: communicate/client.proto

package communicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateClientByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdClient int64 `protobuf:"varint,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
}

func (x *ValidateClientByIdRequest) Reset() {
	*x = ValidateClientByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateClientByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientByIdRequest) ProtoMessage() {}

func (x *ValidateClientByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientByIdRequest.ProtoReflect.Descriptor instead.
func (*ValidateClientByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateClientByIdRequest) GetIdClient() int64 {
	if x != nil {
		return x.IdClient
	}
	return 0
}

type ValidateClientByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidateClientByIdResponse) Reset() {
	*x = ValidateClientByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateClientByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientByIdResponse) ProtoMessage() {}

func (x *ValidateClientByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientByIdResponse.ProtoReflect.Descriptor instead.
func (*ValidateClientByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateClientByIdResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{2}
}

func (x *Client) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Client) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type DataClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client []*Client `protobuf:"bytes,1,rep,name=client,proto3" json:"client,omitempty"`
}

func (x *DataClient) Reset() {
	*x = DataClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataClient) ProtoMessage() {}

func (x *DataClient) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataClient.ProtoReflect.Descriptor instead.
func (*DataClient) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{3}
}

func (x *DataClient) GetClient() []*Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type ClientListAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientListAllRequest) Reset() {
	*x = ClientListAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientListAllRequest) ProtoMessage() {}

func (x *ClientListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientListAllRequest.ProtoReflect.Descriptor instead.
func (*ClientListAllRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{4}
}

func (x *ClientListAllRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ClientListAllRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ClientListAllRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ClientListAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *DataClient `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Page  int64       `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64       `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ClientListAllResponse) Reset() {
	*x = ClientListAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientListAllResponse) ProtoMessage() {}

func (x *ClientListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientListAllResponse.ProtoReflect.Descriptor instead.
func (*ClientListAllResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{5}
}

func (x *ClientListAllResponse) GetData() *DataClient {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientListAllResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ClientListAllResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ClientListAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{6}
}

func (x *CreateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{7}
}

func (x *CreateClientResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ValidateClientCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ValidateClientCreateRequest) Reset() {
	*x = ValidateClientCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateClientCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientCreateRequest) ProtoMessage() {}

func (x *ValidateClientCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientCreateRequest.ProtoReflect.Descriptor instead.
func (*ValidateClientCreateRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateClientCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateClientCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ValidateClientCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidateClientCreateResponse) Reset() {
	*x = ValidateClientCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateClientCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientCreateResponse) ProtoMessage() {}

func (x *ValidateClientCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientCreateResponse.ProtoReflect.Descriptor instead.
func (*ValidateClientCreateResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateClientCreateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type DeleteClientByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteClientByIdRequest) Reset() {
	*x = DeleteClientByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClientByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientByIdRequest) ProtoMessage() {}

func (x *DeleteClientByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteClientByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteClientByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteClientByIdResponse) Reset() {
	*x = DeleteClientByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteClientByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientByIdResponse) ProtoMessage() {}

func (x *DeleteClientByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteClientByIdResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UpdateClientByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UpdateClientByIdRequest) Reset() {
	*x = UpdateClientByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClientByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientByIdRequest) ProtoMessage() {}

func (x *UpdateClientByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateClientByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateClientByIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClientByIdRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateClientByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateClientByIdResponse) Reset() {
	*x = UpdateClientByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateClientByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientByIdResponse) ProtoMessage() {}

func (x *UpdateClientByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateClientByIdResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type ListOneClientByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListOneClientByIdRequest) Reset() {
	*x = ListOneClientByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneClientByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneClientByIdRequest) ProtoMessage() {}

func (x *ListOneClientByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneClientByIdRequest.ProtoReflect.Descriptor instead.
func (*ListOneClientByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{14}
}

func (x *ListOneClientByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListOneClientByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ListOneClientByIdResponse) Reset() {
	*x = ListOneClientByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_client_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneClientByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneClientByIdResponse) ProtoMessage() {}

func (x *ListOneClientByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_client_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneClientByIdResponse.ProtoReflect.Descriptor instead.
func (*ListOneClientByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_client_proto_rawDescGZIP(), []int{15}
}

func (x *ListOneClientByIdResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

var File_communicate_client_proto protoreflect.FileDescriptor

var file_communicate_client_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x19, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x1a, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x22, 0x2d, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x1f, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x22, 0x54, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x78, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x55, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x47, 0x0a, 0x1b, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x34, 0x0a, 0x1c, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x53, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x34,
	0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3c, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x32, 0x9f,
	0x04, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x12, 0x4f, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x15, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x13, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x12, 0x1c, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communicate_client_proto_rawDescOnce sync.Once
	file_communicate_client_proto_rawDescData = file_communicate_client_proto_rawDesc
)

func file_communicate_client_proto_rawDescGZIP() []byte {
	file_communicate_client_proto_rawDescOnce.Do(func() {
		file_communicate_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_communicate_client_proto_rawDescData)
	})
	return file_communicate_client_proto_rawDescData
}

var file_communicate_client_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_communicate_client_proto_goTypes = []interface{}{
	(*ValidateClientByIdRequest)(nil),    // 0: ValidateClientByIdRequest
	(*ValidateClientByIdResponse)(nil),   // 1: ValidateClientByIdResponse
	(*Client)(nil),                       // 2: Client
	(*DataClient)(nil),                   // 3: DataClient
	(*ClientListAllRequest)(nil),         // 4: ClientListAllRequest
	(*ClientListAllResponse)(nil),        // 5: ClientListAllResponse
	(*CreateClientRequest)(nil),          // 6: CreateClientRequest
	(*CreateClientResponse)(nil),         // 7: CreateClientResponse
	(*ValidateClientCreateRequest)(nil),  // 8: ValidateClientCreateRequest
	(*ValidateClientCreateResponse)(nil), // 9: ValidateClientCreateResponse
	(*DeleteClientByIdRequest)(nil),      // 10: DeleteClientByIdRequest
	(*DeleteClientByIdResponse)(nil),     // 11: DeleteClientByIdResponse
	(*UpdateClientByIdRequest)(nil),      // 12: UpdateClientByIdRequest
	(*UpdateClientByIdResponse)(nil),     // 13: UpdateClientByIdResponse
	(*ListOneClientByIdRequest)(nil),     // 14: ListOneClientByIdRequest
	(*ListOneClientByIdResponse)(nil),    // 15: ListOneClientByIdResponse
}
var file_communicate_client_proto_depIdxs = []int32{
	2,  // 0: DataClient.client:type_name -> Client
	3,  // 1: ClientListAllResponse.data:type_name -> DataClient
	2,  // 2: ListOneClientByIdResponse.client:type_name -> Client
	0,  // 3: ClientCommunicate.ValidateClientById:input_type -> ValidateClientByIdRequest
	4,  // 4: ClientCommunicate.ClientListAll:input_type -> ClientListAllRequest
	6,  // 5: ClientCommunicate.CreateClient:input_type -> CreateClientRequest
	14, // 6: ClientCommunicate.ListOneClientById:input_type -> ListOneClientByIdRequest
	12, // 7: ClientCommunicate.UpdateClientById:input_type -> UpdateClientByIdRequest
	10, // 8: ClientCommunicate.DeleteClientById:input_type -> DeleteClientByIdRequest
	8,  // 9: ClientCommunicate.ValidateClientExist:input_type -> ValidateClientCreateRequest
	1,  // 10: ClientCommunicate.ValidateClientById:output_type -> ValidateClientByIdResponse
	5,  // 11: ClientCommunicate.ClientListAll:output_type -> ClientListAllResponse
	7,  // 12: ClientCommunicate.CreateClient:output_type -> CreateClientResponse
	15, // 13: ClientCommunicate.ListOneClientById:output_type -> ListOneClientByIdResponse
	13, // 14: ClientCommunicate.UpdateClientById:output_type -> UpdateClientByIdResponse
	11, // 15: ClientCommunicate.DeleteClientById:output_type -> DeleteClientByIdResponse
	9,  // 16: ClientCommunicate.ValidateClientExist:output_type -> ValidateClientCreateResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_communicate_client_proto_init() }
func file_communicate_client_proto_init() {
	if File_communicate_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communicate_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateClientByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateClientByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientListAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientListAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateClientCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateClientCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClientByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteClientByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClientByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateClientByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneClientByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_client_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneClientByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communicate_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communicate_client_proto_goTypes,
		DependencyIndexes: file_communicate_client_proto_depIdxs,
		MessageInfos:      file_communicate_client_proto_msgTypes,
	}.Build()
	File_communicate_client_proto = out.File
	file_communicate_client_proto_rawDesc = nil
	file_communicate_client_proto_goTypes = nil
	file_communicate_client_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientCommunicateClient is the client API for ClientCommunicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientCommunicateClient interface {
	ValidateClientById(ctx context.Context, in *ValidateClientByIdRequest, opts ...grpc.CallOption) (*ValidateClientByIdResponse, error)
	ClientListAll(ctx context.Context, in *ClientListAllRequest, opts ...grpc.CallOption) (*ClientListAllResponse, error)
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	ListOneClientById(ctx context.Context, in *ListOneClientByIdRequest, opts ...grpc.CallOption) (*ListOneClientByIdResponse, error)
	UpdateClientById(ctx context.Context, in *UpdateClientByIdRequest, opts ...grpc.CallOption) (*UpdateClientByIdResponse, error)
	DeleteClientById(ctx context.Context, in *DeleteClientByIdRequest, opts ...grpc.CallOption) (*DeleteClientByIdResponse, error)
	ValidateClientExist(ctx context.Context, in *ValidateClientCreateRequest, opts ...grpc.CallOption) (*ValidateClientCreateResponse, error)
}

type clientCommunicateClient struct {
	cc grpc.ClientConnInterface
}

func NewClientCommunicateClient(cc grpc.ClientConnInterface) ClientCommunicateClient {
	return &clientCommunicateClient{cc}
}

func (c *clientCommunicateClient) ValidateClientById(ctx context.Context, in *ValidateClientByIdRequest, opts ...grpc.CallOption) (*ValidateClientByIdResponse, error) {
	out := new(ValidateClientByIdResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/ValidateClientById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientCommunicateClient) ClientListAll(ctx context.Context, in *ClientListAllRequest, opts ...grpc.CallOption) (*ClientListAllResponse, error) {
	out := new(ClientListAllResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/ClientListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientCommunicateClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientCommunicateClient) ListOneClientById(ctx context.Context, in *ListOneClientByIdRequest, opts ...grpc.CallOption) (*ListOneClientByIdResponse, error) {
	out := new(ListOneClientByIdResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/ListOneClientById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientCommunicateClient) UpdateClientById(ctx context.Context, in *UpdateClientByIdRequest, opts ...grpc.CallOption) (*UpdateClientByIdResponse, error) {
	out := new(UpdateClientByIdResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/UpdateClientById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientCommunicateClient) DeleteClientById(ctx context.Context, in *DeleteClientByIdRequest, opts ...grpc.CallOption) (*DeleteClientByIdResponse, error) {
	out := new(DeleteClientByIdResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/DeleteClientById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientCommunicateClient) ValidateClientExist(ctx context.Context, in *ValidateClientCreateRequest, opts ...grpc.CallOption) (*ValidateClientCreateResponse, error) {
	out := new(ValidateClientCreateResponse)
	err := c.cc.Invoke(ctx, "/ClientCommunicate/ValidateClientExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientCommunicateServer is the server API for ClientCommunicate service.
type ClientCommunicateServer interface {
	ValidateClientById(context.Context, *ValidateClientByIdRequest) (*ValidateClientByIdResponse, error)
	ClientListAll(context.Context, *ClientListAllRequest) (*ClientListAllResponse, error)
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	ListOneClientById(context.Context, *ListOneClientByIdRequest) (*ListOneClientByIdResponse, error)
	UpdateClientById(context.Context, *UpdateClientByIdRequest) (*UpdateClientByIdResponse, error)
	DeleteClientById(context.Context, *DeleteClientByIdRequest) (*DeleteClientByIdResponse, error)
	ValidateClientExist(context.Context, *ValidateClientCreateRequest) (*ValidateClientCreateResponse, error)
}

// UnimplementedClientCommunicateServer can be embedded to have forward compatible implementations.
type UnimplementedClientCommunicateServer struct {
}

func (*UnimplementedClientCommunicateServer) ValidateClientById(context.Context, *ValidateClientByIdRequest) (*ValidateClientByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateClientById not implemented")
}
func (*UnimplementedClientCommunicateServer) ClientListAll(context.Context, *ClientListAllRequest) (*ClientListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientListAll not implemented")
}
func (*UnimplementedClientCommunicateServer) CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (*UnimplementedClientCommunicateServer) ListOneClientById(context.Context, *ListOneClientByIdRequest) (*ListOneClientByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOneClientById not implemented")
}
func (*UnimplementedClientCommunicateServer) UpdateClientById(context.Context, *UpdateClientByIdRequest) (*UpdateClientByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClientById not implemented")
}
func (*UnimplementedClientCommunicateServer) DeleteClientById(context.Context, *DeleteClientByIdRequest) (*DeleteClientByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClientById not implemented")
}
func (*UnimplementedClientCommunicateServer) ValidateClientExist(context.Context, *ValidateClientCreateRequest) (*ValidateClientCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateClientExist not implemented")
}

func RegisterClientCommunicateServer(s *grpc.Server, srv ClientCommunicateServer) {
	s.RegisterService(&_ClientCommunicate_serviceDesc, srv)
}

func _ClientCommunicate_ValidateClientById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateClientByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).ValidateClientById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/ValidateClientById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).ValidateClientById(ctx, req.(*ValidateClientByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientCommunicate_ClientListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).ClientListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/ClientListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).ClientListAll(ctx, req.(*ClientListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientCommunicate_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientCommunicate_ListOneClientById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOneClientByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).ListOneClientById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/ListOneClientById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).ListOneClientById(ctx, req.(*ListOneClientByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientCommunicate_UpdateClientById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).UpdateClientById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/UpdateClientById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).UpdateClientById(ctx, req.(*UpdateClientByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientCommunicate_DeleteClientById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).DeleteClientById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/DeleteClientById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).DeleteClientById(ctx, req.(*DeleteClientByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientCommunicate_ValidateClientExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateClientCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCommunicateServer).ValidateClientExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ClientCommunicate/ValidateClientExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCommunicateServer).ValidateClientExist(ctx, req.(*ValidateClientCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientCommunicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ClientCommunicate",
	HandlerType: (*ClientCommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateClientById",
			Handler:    _ClientCommunicate_ValidateClientById_Handler,
		},
		{
			MethodName: "ClientListAll",
			Handler:    _ClientCommunicate_ClientListAll_Handler,
		},
		{
			MethodName: "CreateClient",
			Handler:    _ClientCommunicate_CreateClient_Handler,
		},
		{
			MethodName: "ListOneClientById",
			Handler:    _ClientCommunicate_ListOneClientById_Handler,
		},
		{
			MethodName: "UpdateClientById",
			Handler:    _ClientCommunicate_UpdateClientById_Handler,
		},
		{
			MethodName: "DeleteClientById",
			Handler:    _ClientCommunicate_DeleteClientById_Handler,
		},
		{
			MethodName: "ValidateClientExist",
			Handler:    _ClientCommunicate_ValidateClientExist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicate/client.proto",
}
