// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: communicate/courrier.proto

package communicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Documentation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Documentation) Reset() {
	*x = Documentation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Documentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Documentation) ProtoMessage() {}

func (x *Documentation) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Documentation.ProtoReflect.Descriptor instead.
func (*Documentation) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{0}
}

func (x *Documentation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Documentation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClientLg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientLg) Reset() {
	*x = ClientLg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLg) ProtoMessage() {}

func (x *ClientLg) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLg.ProtoReflect.Descriptor instead.
func (*ClientLg) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{1}
}

func (x *ClientLg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientLg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DepositLg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DepositLg) Reset() {
	*x = DepositLg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositLg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositLg) ProtoMessage() {}

func (x *DepositLg) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositLg.ProtoReflect.Descriptor instead.
func (*DepositLg) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{2}
}

func (x *DepositLg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepositLg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProductLg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProductLg) Reset() {
	*x = ProductLg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductLg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductLg) ProtoMessage() {}

func (x *ProductLg) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductLg.ProtoReflect.Descriptor instead.
func (*ProductLg) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{3}
}

func (x *ProductLg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductLg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Courier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product   *ProductLg     `protobuf:"bytes,2,opt,name=Product,proto3" json:"Product,omitempty"`
	Client    *ClientLg      `protobuf:"bytes,3,opt,name=Client,proto3" json:"Client,omitempty"`
	Deposit   *DepositLg     `protobuf:"bytes,4,opt,name=Deposit,proto3" json:"Deposit,omitempty"`
	Delivered bool           `protobuf:"varint,5,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Doc       *Documentation `protobuf:"bytes,6,opt,name=doc,proto3" json:"doc,omitempty"`
}

func (x *Courier) Reset() {
	*x = Courier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Courier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courier) ProtoMessage() {}

func (x *Courier) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courier.ProtoReflect.Descriptor instead.
func (*Courier) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{4}
}

func (x *Courier) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Courier) GetProduct() *ProductLg {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Courier) GetClient() *ClientLg {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *Courier) GetDeposit() *DepositLg {
	if x != nil {
		return x.Deposit
	}
	return nil
}

func (x *Courier) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *Courier) GetDoc() *Documentation {
	if x != nil {
		return x.Doc
	}
	return nil
}

type DataCourier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courier []*Courier `protobuf:"bytes,1,rep,name=courier,proto3" json:"courier,omitempty"`
}

func (x *DataCourier) Reset() {
	*x = DataCourier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCourier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCourier) ProtoMessage() {}

func (x *DataCourier) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCourier.ProtoReflect.Descriptor instead.
func (*DataCourier) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{5}
}

func (x *DataCourier) GetCourier() []*Courier {
	if x != nil {
		return x.Courier
	}
	return nil
}

type CourierListAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CourierListAllRequest) Reset() {
	*x = CourierListAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierListAllRequest) ProtoMessage() {}

func (x *CourierListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierListAllRequest.ProtoReflect.Descriptor instead.
func (*CourierListAllRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{6}
}

func (x *CourierListAllRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CourierListAllRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CourierListAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *DataCourier `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Page  int64        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64        `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total int64        `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CourierListAllResponse) Reset() {
	*x = CourierListAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierListAllResponse) ProtoMessage() {}

func (x *CourierListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierListAllResponse.ProtoReflect.Descriptor instead.
func (*CourierListAllResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{7}
}

func (x *CourierListAllResponse) GetData() *DataCourier {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CourierListAllResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CourierListAllResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CourierListAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateCourierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProduct int64 `protobuf:"varint,1,opt,name=idProduct,proto3" json:"idProduct,omitempty"`
	IdClient  int64 `protobuf:"varint,2,opt,name=idClient,proto3" json:"idClient,omitempty"`
	IdDeposit int64 `protobuf:"varint,3,opt,name=idDeposit,proto3" json:"idDeposit,omitempty"`
}

func (x *CreateCourierRequest) Reset() {
	*x = CreateCourierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCourierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourierRequest) ProtoMessage() {}

func (x *CreateCourierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourierRequest.ProtoReflect.Descriptor instead.
func (*CreateCourierRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCourierRequest) GetIdProduct() int64 {
	if x != nil {
		return x.IdProduct
	}
	return 0
}

func (x *CreateCourierRequest) GetIdClient() int64 {
	if x != nil {
		return x.IdClient
	}
	return 0
}

func (x *CreateCourierRequest) GetIdDeposit() int64 {
	if x != nil {
		return x.IdDeposit
	}
	return 0
}

type CreateCourierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *CreateCourierResponse) Reset() {
	*x = CreateCourierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCourierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourierResponse) ProtoMessage() {}

func (x *CreateCourierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourierResponse.ProtoReflect.Descriptor instead.
func (*CreateCourierResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCourierResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type DeleteCourierByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCourierByIdRequest) Reset() {
	*x = DeleteCourierByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourierByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourierByIdRequest) ProtoMessage() {}

func (x *DeleteCourierByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourierByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourierByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCourierByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCourierByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteCourierByIdResponse) Reset() {
	*x = DeleteCourierByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourierByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourierByIdResponse) ProtoMessage() {}

func (x *DeleteCourierByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourierByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourierByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCourierByIdResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UpdateCourierByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdProduct int64          `protobuf:"varint,2,opt,name=idProduct,proto3" json:"idProduct,omitempty"`
	IdClient  int64          `protobuf:"varint,3,opt,name=idClient,proto3" json:"idClient,omitempty"`
	IdDeposit int64          `protobuf:"varint,4,opt,name=idDeposit,proto3" json:"idDeposit,omitempty"`
	Delivered bool           `protobuf:"varint,5,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Doc       *Documentation `protobuf:"bytes,6,opt,name=doc,proto3" json:"doc,omitempty"`
}

func (x *UpdateCourierByIdRequest) Reset() {
	*x = UpdateCourierByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCourierByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourierByIdRequest) ProtoMessage() {}

func (x *UpdateCourierByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourierByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourierByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCourierByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCourierByIdRequest) GetIdProduct() int64 {
	if x != nil {
		return x.IdProduct
	}
	return 0
}

func (x *UpdateCourierByIdRequest) GetIdClient() int64 {
	if x != nil {
		return x.IdClient
	}
	return 0
}

func (x *UpdateCourierByIdRequest) GetIdDeposit() int64 {
	if x != nil {
		return x.IdDeposit
	}
	return 0
}

func (x *UpdateCourierByIdRequest) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *UpdateCourierByIdRequest) GetDoc() *Documentation {
	if x != nil {
		return x.Doc
	}
	return nil
}

type UpdateCourierByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateCourierByIdResponse) Reset() {
	*x = UpdateCourierByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCourierByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourierByIdResponse) ProtoMessage() {}

func (x *UpdateCourierByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourierByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourierByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateCourierByIdResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type ListOneCourierByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListOneCourierByIdRequest) Reset() {
	*x = ListOneCourierByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneCourierByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneCourierByIdRequest) ProtoMessage() {}

func (x *ListOneCourierByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneCourierByIdRequest.ProtoReflect.Descriptor instead.
func (*ListOneCourierByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{14}
}

func (x *ListOneCourierByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListOneCourierByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courier *Courier `protobuf:"bytes,1,opt,name=courier,proto3" json:"courier,omitempty"`
}

func (x *ListOneCourierByIdResponse) Reset() {
	*x = ListOneCourierByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneCourierByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneCourierByIdResponse) ProtoMessage() {}

func (x *ListOneCourierByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneCourierByIdResponse.ProtoReflect.Descriptor instead.
func (*ListOneCourierByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{15}
}

func (x *ListOneCourierByIdResponse) GetCourier() *Courier {
	if x != nil {
		return x.Courier
	}
	return nil
}

type CourierValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdProduct int64 `protobuf:"varint,2,opt,name=idProduct,proto3" json:"idProduct,omitempty"`
}

func (x *CourierValidateRequest) Reset() {
	*x = CourierValidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierValidateRequest) ProtoMessage() {}

func (x *CourierValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierValidateRequest.ProtoReflect.Descriptor instead.
func (*CourierValidateRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{16}
}

func (x *CourierValidateRequest) GetIdProduct() int64 {
	if x != nil {
		return x.IdProduct
	}
	return 0
}

type CourierValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *CourierValidateResponse) Reset() {
	*x = CourierValidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courrier_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierValidateResponse) ProtoMessage() {}

func (x *CourierValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courrier_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierValidateResponse.ProtoReflect.Descriptor instead.
func (*CourierValidateResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courrier_proto_rawDescGZIP(), []int{17}
}

func (x *CourierValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_communicate_courrier_proto protoreflect.FileDescriptor

var file_communicate_courrier_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x6f,
	0x75, 0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x0d,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4c, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x4c, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x4c, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xc8, 0x01, 0x0a, 0x07, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x4c, 0x67, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x06, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4c, 0x67, 0x52, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4c, 0x67, 0x52, 0x07, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x65, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x03, 0x64, 0x6f, 0x63, 0x22, 0x31, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x15, 0x43, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x7a, 0x0a, 0x16, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x6e, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x69, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x64, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0xc2, 0x01, 0x0a,
	0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x64, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12,
	0x20, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x6f,
	0x63, 0x22, 0x35, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x07,
	0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x16, 0x43, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22,
	0x2f, 0x0a, 0x17, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x32, 0xd0, 0x03, 0x0a, 0x12, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x43, 0x6f, 0x75,
	0x72, 0x69, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x16, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e,
	0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x6e, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communicate_courrier_proto_rawDescOnce sync.Once
	file_communicate_courrier_proto_rawDescData = file_communicate_courrier_proto_rawDesc
)

func file_communicate_courrier_proto_rawDescGZIP() []byte {
	file_communicate_courrier_proto_rawDescOnce.Do(func() {
		file_communicate_courrier_proto_rawDescData = protoimpl.X.CompressGZIP(file_communicate_courrier_proto_rawDescData)
	})
	return file_communicate_courrier_proto_rawDescData
}

var file_communicate_courrier_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_communicate_courrier_proto_goTypes = []interface{}{
	(*Documentation)(nil),              // 0: Documentation
	(*ClientLg)(nil),                   // 1: ClientLg
	(*DepositLg)(nil),                  // 2: DepositLg
	(*ProductLg)(nil),                  // 3: ProductLg
	(*Courier)(nil),                    // 4: Courier
	(*DataCourier)(nil),                // 5: DataCourier
	(*CourierListAllRequest)(nil),      // 6: CourierListAllRequest
	(*CourierListAllResponse)(nil),     // 7: CourierListAllResponse
	(*CreateCourierRequest)(nil),       // 8: CreateCourierRequest
	(*CreateCourierResponse)(nil),      // 9: CreateCourierResponse
	(*DeleteCourierByIdRequest)(nil),   // 10: DeleteCourierByIdRequest
	(*DeleteCourierByIdResponse)(nil),  // 11: DeleteCourierByIdResponse
	(*UpdateCourierByIdRequest)(nil),   // 12: UpdateCourierByIdRequest
	(*UpdateCourierByIdResponse)(nil),  // 13: UpdateCourierByIdResponse
	(*ListOneCourierByIdRequest)(nil),  // 14: ListOneCourierByIdRequest
	(*ListOneCourierByIdResponse)(nil), // 15: ListOneCourierByIdResponse
	(*CourierValidateRequest)(nil),     // 16: CourierValidateRequest
	(*CourierValidateResponse)(nil),    // 17: CourierValidateResponse
}
var file_communicate_courrier_proto_depIdxs = []int32{
	3,  // 0: Courier.Product:type_name -> ProductLg
	1,  // 1: Courier.Client:type_name -> ClientLg
	2,  // 2: Courier.Deposit:type_name -> DepositLg
	0,  // 3: Courier.doc:type_name -> Documentation
	4,  // 4: DataCourier.courier:type_name -> Courier
	5,  // 5: CourierListAllResponse.data:type_name -> DataCourier
	0,  // 6: UpdateCourierByIdRequest.doc:type_name -> Documentation
	4,  // 7: ListOneCourierByIdResponse.courier:type_name -> Courier
	16, // 8: CourierCommunicate.ValidateCourier:input_type -> CourierValidateRequest
	6,  // 9: CourierCommunicate.CourierListAll:input_type -> CourierListAllRequest
	8,  // 10: CourierCommunicate.CreateCourier:input_type -> CreateCourierRequest
	14, // 11: CourierCommunicate.ListOneCourierById:input_type -> ListOneCourierByIdRequest
	12, // 12: CourierCommunicate.UpdateCourierById:input_type -> UpdateCourierByIdRequest
	10, // 13: CourierCommunicate.DeleteCourierById:input_type -> DeleteCourierByIdRequest
	17, // 14: CourierCommunicate.ValidateCourier:output_type -> CourierValidateResponse
	7,  // 15: CourierCommunicate.CourierListAll:output_type -> CourierListAllResponse
	9,  // 16: CourierCommunicate.CreateCourier:output_type -> CreateCourierResponse
	15, // 17: CourierCommunicate.ListOneCourierById:output_type -> ListOneCourierByIdResponse
	13, // 18: CourierCommunicate.UpdateCourierById:output_type -> UpdateCourierByIdResponse
	11, // 19: CourierCommunicate.DeleteCourierById:output_type -> DeleteCourierByIdResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_communicate_courrier_proto_init() }
func file_communicate_courrier_proto_init() {
	if File_communicate_courrier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communicate_courrier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Documentation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositLg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductLg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Courier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCourier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierListAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierListAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCourierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCourierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourierByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourierByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCourierByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCourierByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneCourierByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneCourierByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierValidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courrier_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierValidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communicate_courrier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communicate_courrier_proto_goTypes,
		DependencyIndexes: file_communicate_courrier_proto_depIdxs,
		MessageInfos:      file_communicate_courrier_proto_msgTypes,
	}.Build()
	File_communicate_courrier_proto = out.File
	file_communicate_courrier_proto_rawDesc = nil
	file_communicate_courrier_proto_goTypes = nil
	file_communicate_courrier_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CourierCommunicateClient is the client API for CourierCommunicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CourierCommunicateClient interface {
	ValidateCourier(ctx context.Context, in *CourierValidateRequest, opts ...grpc.CallOption) (*CourierValidateResponse, error)
	CourierListAll(ctx context.Context, in *CourierListAllRequest, opts ...grpc.CallOption) (*CourierListAllResponse, error)
	CreateCourier(ctx context.Context, in *CreateCourierRequest, opts ...grpc.CallOption) (*CreateCourierResponse, error)
	ListOneCourierById(ctx context.Context, in *ListOneCourierByIdRequest, opts ...grpc.CallOption) (*ListOneCourierByIdResponse, error)
	UpdateCourierById(ctx context.Context, in *UpdateCourierByIdRequest, opts ...grpc.CallOption) (*UpdateCourierByIdResponse, error)
	DeleteCourierById(ctx context.Context, in *DeleteCourierByIdRequest, opts ...grpc.CallOption) (*DeleteCourierByIdResponse, error)
}

type courierCommunicateClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierCommunicateClient(cc grpc.ClientConnInterface) CourierCommunicateClient {
	return &courierCommunicateClient{cc}
}

func (c *courierCommunicateClient) ValidateCourier(ctx context.Context, in *CourierValidateRequest, opts ...grpc.CallOption) (*CourierValidateResponse, error) {
	out := new(CourierValidateResponse)
	err := c.cc.Invoke(ctx, "/CourierCommunicate/ValidateCourier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierCommunicateClient) CourierListAll(ctx context.Context, in *CourierListAllRequest, opts ...grpc.CallOption) (*CourierListAllResponse, error) {
	out := new(CourierListAllResponse)
	err := c.cc.Invoke(ctx, "/CourierCommunicate/CourierListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierCommunicateClient) CreateCourier(ctx context.Context, in *CreateCourierRequest, opts ...grpc.CallOption) (*CreateCourierResponse, error) {
	out := new(CreateCourierResponse)
	err := c.cc.Invoke(ctx, "/CourierCommunicate/CreateCourier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierCommunicateClient) ListOneCourierById(ctx context.Context, in *ListOneCourierByIdRequest, opts ...grpc.CallOption) (*ListOneCourierByIdResponse, error) {
	out := new(ListOneCourierByIdResponse)
	err := c.cc.Invoke(ctx, "/CourierCommunicate/ListOneCourierById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierCommunicateClient) UpdateCourierById(ctx context.Context, in *UpdateCourierByIdRequest, opts ...grpc.CallOption) (*UpdateCourierByIdResponse, error) {
	out := new(UpdateCourierByIdResponse)
	err := c.cc.Invoke(ctx, "/CourierCommunicate/UpdateCourierById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierCommunicateClient) DeleteCourierById(ctx context.Context, in *DeleteCourierByIdRequest, opts ...grpc.CallOption) (*DeleteCourierByIdResponse, error) {
	out := new(DeleteCourierByIdResponse)
	err := c.cc.Invoke(ctx, "/CourierCommunicate/DeleteCourierById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierCommunicateServer is the server API for CourierCommunicate service.
type CourierCommunicateServer interface {
	ValidateCourier(context.Context, *CourierValidateRequest) (*CourierValidateResponse, error)
	CourierListAll(context.Context, *CourierListAllRequest) (*CourierListAllResponse, error)
	CreateCourier(context.Context, *CreateCourierRequest) (*CreateCourierResponse, error)
	ListOneCourierById(context.Context, *ListOneCourierByIdRequest) (*ListOneCourierByIdResponse, error)
	UpdateCourierById(context.Context, *UpdateCourierByIdRequest) (*UpdateCourierByIdResponse, error)
	DeleteCourierById(context.Context, *DeleteCourierByIdRequest) (*DeleteCourierByIdResponse, error)
}

// UnimplementedCourierCommunicateServer can be embedded to have forward compatible implementations.
type UnimplementedCourierCommunicateServer struct {
}

func (*UnimplementedCourierCommunicateServer) ValidateCourier(context.Context, *CourierValidateRequest) (*CourierValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCourier not implemented")
}
func (*UnimplementedCourierCommunicateServer) CourierListAll(context.Context, *CourierListAllRequest) (*CourierListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CourierListAll not implemented")
}
func (*UnimplementedCourierCommunicateServer) CreateCourier(context.Context, *CreateCourierRequest) (*CreateCourierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourier not implemented")
}
func (*UnimplementedCourierCommunicateServer) ListOneCourierById(context.Context, *ListOneCourierByIdRequest) (*ListOneCourierByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOneCourierById not implemented")
}
func (*UnimplementedCourierCommunicateServer) UpdateCourierById(context.Context, *UpdateCourierByIdRequest) (*UpdateCourierByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCourierById not implemented")
}
func (*UnimplementedCourierCommunicateServer) DeleteCourierById(context.Context, *DeleteCourierByIdRequest) (*DeleteCourierByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourierById not implemented")
}

func RegisterCourierCommunicateServer(s *grpc.Server, srv CourierCommunicateServer) {
	s.RegisterService(&_CourierCommunicate_serviceDesc, srv)
}

func _CourierCommunicate_ValidateCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourierValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierCommunicateServer).ValidateCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierCommunicate/ValidateCourier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierCommunicateServer).ValidateCourier(ctx, req.(*CourierValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierCommunicate_CourierListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourierListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierCommunicateServer).CourierListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierCommunicate/CourierListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierCommunicateServer).CourierListAll(ctx, req.(*CourierListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierCommunicate_CreateCourier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierCommunicateServer).CreateCourier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierCommunicate/CreateCourier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierCommunicateServer).CreateCourier(ctx, req.(*CreateCourierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierCommunicate_ListOneCourierById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOneCourierByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierCommunicateServer).ListOneCourierById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierCommunicate/ListOneCourierById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierCommunicateServer).ListOneCourierById(ctx, req.(*ListOneCourierByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierCommunicate_UpdateCourierById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCourierByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierCommunicateServer).UpdateCourierById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierCommunicate/UpdateCourierById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierCommunicateServer).UpdateCourierById(ctx, req.(*UpdateCourierByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierCommunicate_DeleteCourierById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourierByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierCommunicateServer).DeleteCourierById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierCommunicate/DeleteCourierById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierCommunicateServer).DeleteCourierById(ctx, req.(*DeleteCourierByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CourierCommunicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CourierCommunicate",
	HandlerType: (*CourierCommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateCourier",
			Handler:    _CourierCommunicate_ValidateCourier_Handler,
		},
		{
			MethodName: "CourierListAll",
			Handler:    _CourierCommunicate_CourierListAll_Handler,
		},
		{
			MethodName: "CreateCourier",
			Handler:    _CourierCommunicate_CreateCourier_Handler,
		},
		{
			MethodName: "ListOneCourierById",
			Handler:    _CourierCommunicate_ListOneCourierById_Handler,
		},
		{
			MethodName: "UpdateCourierById",
			Handler:    _CourierCommunicate_UpdateCourierById_Handler,
		},
		{
			MethodName: "DeleteCourierById",
			Handler:    _CourierCommunicate_DeleteCourierById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicate/courrier.proto",
}
