// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: communicate/courierRoutes.proto

package communicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Doc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Doc) Reset() {
	*x = Doc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doc) ProtoMessage() {}

func (x *Doc) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doc.ProtoReflect.Descriptor instead.
func (*Doc) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{0}
}

func (x *Doc) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Doc) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CourieRouteAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit     int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Delivered bool  `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"`
	IdDriver  int64 `protobuf:"varint,4,opt,name=idDriver,proto3" json:"idDriver,omitempty"`
}

func (x *CourieRouteAllRequest) Reset() {
	*x = CourieRouteAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourieRouteAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourieRouteAllRequest) ProtoMessage() {}

func (x *CourieRouteAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourieRouteAllRequest.ProtoReflect.Descriptor instead.
func (*CourieRouteAllRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{1}
}

func (x *CourieRouteAllRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CourieRouteAllRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CourieRouteAllRequest) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *CourieRouteAllRequest) GetIdDriver() int64 {
	if x != nil {
		return x.IdDriver
	}
	return 0
}

type CourierRouteAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *DataCourierRoute `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Page  int64             `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64             `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total int64             `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CourierRouteAllResponse) Reset() {
	*x = CourierRouteAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierRouteAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRouteAllResponse) ProtoMessage() {}

func (x *CourierRouteAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRouteAllResponse.ProtoReflect.Descriptor instead.
func (*CourierRouteAllResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{2}
}

func (x *CourierRouteAllResponse) GetData() *DataCourierRoute {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CourierRouteAllResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CourierRouteAllResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CourierRouteAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DataCourierRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourierRoute []*CourierRoutes `protobuf:"bytes,1,rep,name=courier_route,json=courierRoute,proto3" json:"courier_route,omitempty"`
}

func (x *DataCourierRoute) Reset() {
	*x = DataCourierRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCourierRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCourierRoute) ProtoMessage() {}

func (x *DataCourierRoute) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCourierRoute.ProtoReflect.Descriptor instead.
func (*DataCourierRoute) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{3}
}

func (x *DataCourierRoute) GetCourierRoute() []*CourierRoutes {
	if x != nil {
		return x.CourierRoute
	}
	return nil
}

type Coordenates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat string `protobuf:"bytes,1,opt,name=Lat,proto3" json:"Lat,omitempty"`
	Lng string `protobuf:"bytes,2,opt,name=Lng,proto3" json:"Lng,omitempty"`
}

func (x *Coordenates) Reset() {
	*x = Coordenates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordenates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordenates) ProtoMessage() {}

func (x *Coordenates) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordenates.ProtoReflect.Descriptor instead.
func (*Coordenates) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{4}
}

func (x *Coordenates) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Coordenates) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdCourier int64        `protobuf:"varint,2,opt,name=idCourier,proto3" json:"idCourier,omitempty"`
	Order     int64        `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Init      *Coordenates `protobuf:"bytes,4,opt,name=init,proto3" json:"init,omitempty"`
	Finish    *Coordenates `protobuf:"bytes,5,opt,name=finish,proto3" json:"finish,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{5}
}

func (x *Route) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Route) GetIdCourier() int64 {
	if x != nil {
		return x.IdCourier
	}
	return 0
}

func (x *Route) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Route) GetInit() *Coordenates {
	if x != nil {
		return x.Init
	}
	return nil
}

func (x *Route) GetFinish() *Coordenates {
	if x != nil {
		return x.Finish
	}
	return nil
}

type ClientCr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ClientCr) Reset() {
	*x = ClientCr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCr) ProtoMessage() {}

func (x *ClientCr) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCr.ProtoReflect.Descriptor instead.
func (*ClientCr) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{6}
}

func (x *ClientCr) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientCr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DepositCr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DepositCr) Reset() {
	*x = DepositCr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositCr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositCr) ProtoMessage() {}

func (x *DepositCr) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositCr.ProtoReflect.Descriptor instead.
func (*DepositCr) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{7}
}

func (x *DepositCr) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DepositCr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProductCr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProductCr) Reset() {
	*x = ProductCr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductCr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCr) ProtoMessage() {}

func (x *ProductCr) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCr.ProtoReflect.Descriptor instead.
func (*ProductCr) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{8}
}

func (x *ProductCr) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductCr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CourierRoutes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product   *ProductCr `protobuf:"bytes,2,opt,name=Product,proto3" json:"Product,omitempty"`
	Client    *ClientCr  `protobuf:"bytes,3,opt,name=Client,proto3" json:"Client,omitempty"`
	Deposit   *DepositCr `protobuf:"bytes,4,opt,name=Deposit,proto3" json:"Deposit,omitempty"`
	Delivered bool       `protobuf:"varint,5,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Doc       *Doc       `protobuf:"bytes,6,opt,name=doc,proto3" json:"doc,omitempty"`
	Route     *Route     `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`
}

func (x *CourierRoutes) Reset() {
	*x = CourierRoutes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierRoutes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRoutes) ProtoMessage() {}

func (x *CourierRoutes) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRoutes.ProtoReflect.Descriptor instead.
func (*CourierRoutes) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{9}
}

func (x *CourierRoutes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourierRoutes) GetProduct() *ProductCr {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *CourierRoutes) GetClient() *ClientCr {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *CourierRoutes) GetDeposit() *DepositCr {
	if x != nil {
		return x.Deposit
	}
	return nil
}

func (x *CourierRoutes) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *CourierRoutes) GetDoc() *Doc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *CourierRoutes) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type Courriers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Courriers) Reset() {
	*x = Courriers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Courriers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Courriers) ProtoMessage() {}

func (x *Courriers) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Courriers.ProtoReflect.Descriptor instead.
func (*Courriers) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{10}
}

func (x *Courriers) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateCourierRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdDriver  int64        `protobuf:"varint,1,opt,name=idDriver,proto3" json:"idDriver,omitempty"`
	Courriers []*Courriers `protobuf:"bytes,2,rep,name=courriers,proto3" json:"courriers,omitempty"`
}

func (x *CreateCourierRoutesRequest) Reset() {
	*x = CreateCourierRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCourierRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourierRoutesRequest) ProtoMessage() {}

func (x *CreateCourierRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourierRoutesRequest.ProtoReflect.Descriptor instead.
func (*CreateCourierRoutesRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCourierRoutesRequest) GetIdDriver() int64 {
	if x != nil {
		return x.IdDriver
	}
	return 0
}

func (x *CreateCourierRoutesRequest) GetCourriers() []*Courriers {
	if x != nil {
		return x.Courriers
	}
	return nil
}

type CreateCourierRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=Created,proto3" json:"Created,omitempty"`
}

func (x *CreateCourierRoutesResponse) Reset() {
	*x = CreateCourierRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCourierRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourierRoutesResponse) ProtoMessage() {}

func (x *CreateCourierRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourierRoutesResponse.ProtoReflect.Descriptor instead.
func (*CreateCourierRoutesResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCourierRoutesResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type CourierRouteListOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CourierRouteListOneRequest) Reset() {
	*x = CourierRouteListOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierRouteListOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRouteListOneRequest) ProtoMessage() {}

func (x *CourierRouteListOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRouteListOneRequest.ProtoReflect.Descriptor instead.
func (*CourierRouteListOneRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{13}
}

func (x *CourierRouteListOneRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CourierRouteListOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourierRoute *CourierRoutes `protobuf:"bytes,1,opt,name=courier_route,json=courierRoute,proto3" json:"courier_route,omitempty"`
}

func (x *CourierRouteListOneResponse) Reset() {
	*x = CourierRouteListOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourierRouteListOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRouteListOneResponse) ProtoMessage() {}

func (x *CourierRouteListOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRouteListOneResponse.ProtoReflect.Descriptor instead.
func (*CourierRouteListOneResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{14}
}

func (x *CourierRouteListOneResponse) GetCourierRoute() *CourierRoutes {
	if x != nil {
		return x.CourierRoute
	}
	return nil
}

type DeleteCourierRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCourierRouteRequest) Reset() {
	*x = DeleteCourierRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourierRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourierRouteRequest) ProtoMessage() {}

func (x *DeleteCourierRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourierRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourierRouteRequest) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCourierRouteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCourierRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
}

func (x *DeleteCourierRouteResponse) Reset() {
	*x = DeleteCourierRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_courierRoutes_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCourierRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourierRouteResponse) ProtoMessage() {}

func (x *DeleteCourierRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_courierRoutes_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourierRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourierRouteResponse) Descriptor() ([]byte, []int) {
	return file_communicate_courierRoutes_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteCourierRouteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_communicate_courierRoutes_proto protoreflect.FileDescriptor

var file_communicate_courierRoutes_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2f, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x7b, 0x0a, 0x15, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x22,
	0x80, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x47, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65,
	0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65,
	0x72, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0c, 0x63,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x4c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6e, 0x67, 0x22, 0x93,
	0x01, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x64, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x64, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x04,
	0x69, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x24,
	0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x06, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x22, 0x2e, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x43, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xe2, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x43, 0x72, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x21,
	0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x52, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x24, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x72, 0x52, 0x07,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x04, 0x2e, 0x44, 0x6f, 0x63, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x12, 0x1c, 0x0a,
	0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x1b, 0x0a, 0x09, 0x43,
	0x6f, 0x75, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x62, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x12, 0x28, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x72, 0x69, 0x65, 0x72,
	0x73, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x72, 0x72, 0x69, 0x65, 0x72, 0x73, 0x22, 0x37, 0x0a, 0x1b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2c, 0x0a, 0x1a, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x1b, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x33, 0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x0c, 0x63, 0x6f, 0x75, 0x72, 0x69,
	0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x2b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x32, 0xe0, 0x02, 0x0a,
	0x17, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x72,
	0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12,
	0x16, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x41, 0x6c, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65,
	0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x72,
	0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65,
	0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1b, 0x2e,
	0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x43, 0x6f, 0x75,
	0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x72, 0x69, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x75, 0x72, 0x69, 0x65, 0x72,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0e, 0x5a, 0x0c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communicate_courierRoutes_proto_rawDescOnce sync.Once
	file_communicate_courierRoutes_proto_rawDescData = file_communicate_courierRoutes_proto_rawDesc
)

func file_communicate_courierRoutes_proto_rawDescGZIP() []byte {
	file_communicate_courierRoutes_proto_rawDescOnce.Do(func() {
		file_communicate_courierRoutes_proto_rawDescData = protoimpl.X.CompressGZIP(file_communicate_courierRoutes_proto_rawDescData)
	})
	return file_communicate_courierRoutes_proto_rawDescData
}

var file_communicate_courierRoutes_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_communicate_courierRoutes_proto_goTypes = []interface{}{
	(*Doc)(nil),                         // 0: Doc
	(*CourieRouteAllRequest)(nil),       // 1: CourieRouteAllRequest
	(*CourierRouteAllResponse)(nil),     // 2: CourierRouteAllResponse
	(*DataCourierRoute)(nil),            // 3: DataCourierRoute
	(*Coordenates)(nil),                 // 4: Coordenates
	(*Route)(nil),                       // 5: Route
	(*ClientCr)(nil),                    // 6: ClientCr
	(*DepositCr)(nil),                   // 7: DepositCr
	(*ProductCr)(nil),                   // 8: ProductCr
	(*CourierRoutes)(nil),               // 9: CourierRoutes
	(*Courriers)(nil),                   // 10: Courriers
	(*CreateCourierRoutesRequest)(nil),  // 11: CreateCourierRoutesRequest
	(*CreateCourierRoutesResponse)(nil), // 12: CreateCourierRoutesResponse
	(*CourierRouteListOneRequest)(nil),  // 13: CourierRouteListOneRequest
	(*CourierRouteListOneResponse)(nil), // 14: CourierRouteListOneResponse
	(*DeleteCourierRouteRequest)(nil),   // 15: DeleteCourierRouteRequest
	(*DeleteCourierRouteResponse)(nil),  // 16: DeleteCourierRouteResponse
}
var file_communicate_courierRoutes_proto_depIdxs = []int32{
	3,  // 0: CourierRouteAllResponse.data:type_name -> DataCourierRoute
	9,  // 1: DataCourierRoute.courier_route:type_name -> CourierRoutes
	4,  // 2: Route.init:type_name -> Coordenates
	4,  // 3: Route.finish:type_name -> Coordenates
	8,  // 4: CourierRoutes.Product:type_name -> ProductCr
	6,  // 5: CourierRoutes.Client:type_name -> ClientCr
	7,  // 6: CourierRoutes.Deposit:type_name -> DepositCr
	0,  // 7: CourierRoutes.doc:type_name -> Doc
	5,  // 8: CourierRoutes.route:type_name -> Route
	10, // 9: CreateCourierRoutesRequest.courriers:type_name -> Courriers
	9,  // 10: CourierRouteListOneResponse.courier_route:type_name -> CourierRoutes
	1,  // 11: CourierRouteCommunicate.CourierRouteListAll:input_type -> CourieRouteAllRequest
	11, // 12: CourierRouteCommunicate.CreateCorrierRoute:input_type -> CreateCourierRoutesRequest
	13, // 13: CourierRouteCommunicate.CourierRouteListOne:input_type -> CourierRouteListOneRequest
	15, // 14: CourierRouteCommunicate.DeleteCourierRouteById:input_type -> DeleteCourierRouteRequest
	2,  // 15: CourierRouteCommunicate.CourierRouteListAll:output_type -> CourierRouteAllResponse
	12, // 16: CourierRouteCommunicate.CreateCorrierRoute:output_type -> CreateCourierRoutesResponse
	14, // 17: CourierRouteCommunicate.CourierRouteListOne:output_type -> CourierRouteListOneResponse
	16, // 18: CourierRouteCommunicate.DeleteCourierRouteById:output_type -> DeleteCourierRouteResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_communicate_courierRoutes_proto_init() }
func file_communicate_courierRoutes_proto_init() {
	if File_communicate_courierRoutes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communicate_courierRoutes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourieRouteAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierRouteAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCourierRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordenates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositCr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductCr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierRoutes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Courriers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCourierRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCourierRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierRouteListOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourierRouteListOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourierRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_courierRoutes_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCourierRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communicate_courierRoutes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communicate_courierRoutes_proto_goTypes,
		DependencyIndexes: file_communicate_courierRoutes_proto_depIdxs,
		MessageInfos:      file_communicate_courierRoutes_proto_msgTypes,
	}.Build()
	File_communicate_courierRoutes_proto = out.File
	file_communicate_courierRoutes_proto_rawDesc = nil
	file_communicate_courierRoutes_proto_goTypes = nil
	file_communicate_courierRoutes_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CourierRouteCommunicateClient is the client API for CourierRouteCommunicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CourierRouteCommunicateClient interface {
	CourierRouteListAll(ctx context.Context, in *CourieRouteAllRequest, opts ...grpc.CallOption) (*CourierRouteAllResponse, error)
	CreateCorrierRoute(ctx context.Context, in *CreateCourierRoutesRequest, opts ...grpc.CallOption) (*CreateCourierRoutesResponse, error)
	CourierRouteListOne(ctx context.Context, in *CourierRouteListOneRequest, opts ...grpc.CallOption) (*CourierRouteListOneResponse, error)
	DeleteCourierRouteById(ctx context.Context, in *DeleteCourierRouteRequest, opts ...grpc.CallOption) (*DeleteCourierRouteResponse, error)
}

type courierRouteCommunicateClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierRouteCommunicateClient(cc grpc.ClientConnInterface) CourierRouteCommunicateClient {
	return &courierRouteCommunicateClient{cc}
}

func (c *courierRouteCommunicateClient) CourierRouteListAll(ctx context.Context, in *CourieRouteAllRequest, opts ...grpc.CallOption) (*CourierRouteAllResponse, error) {
	out := new(CourierRouteAllResponse)
	err := c.cc.Invoke(ctx, "/CourierRouteCommunicate/CourierRouteListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierRouteCommunicateClient) CreateCorrierRoute(ctx context.Context, in *CreateCourierRoutesRequest, opts ...grpc.CallOption) (*CreateCourierRoutesResponse, error) {
	out := new(CreateCourierRoutesResponse)
	err := c.cc.Invoke(ctx, "/CourierRouteCommunicate/CreateCorrierRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierRouteCommunicateClient) CourierRouteListOne(ctx context.Context, in *CourierRouteListOneRequest, opts ...grpc.CallOption) (*CourierRouteListOneResponse, error) {
	out := new(CourierRouteListOneResponse)
	err := c.cc.Invoke(ctx, "/CourierRouteCommunicate/CourierRouteListOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierRouteCommunicateClient) DeleteCourierRouteById(ctx context.Context, in *DeleteCourierRouteRequest, opts ...grpc.CallOption) (*DeleteCourierRouteResponse, error) {
	out := new(DeleteCourierRouteResponse)
	err := c.cc.Invoke(ctx, "/CourierRouteCommunicate/DeleteCourierRouteById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierRouteCommunicateServer is the server API for CourierRouteCommunicate service.
type CourierRouteCommunicateServer interface {
	CourierRouteListAll(context.Context, *CourieRouteAllRequest) (*CourierRouteAllResponse, error)
	CreateCorrierRoute(context.Context, *CreateCourierRoutesRequest) (*CreateCourierRoutesResponse, error)
	CourierRouteListOne(context.Context, *CourierRouteListOneRequest) (*CourierRouteListOneResponse, error)
	DeleteCourierRouteById(context.Context, *DeleteCourierRouteRequest) (*DeleteCourierRouteResponse, error)
}

// UnimplementedCourierRouteCommunicateServer can be embedded to have forward compatible implementations.
type UnimplementedCourierRouteCommunicateServer struct {
}

func (*UnimplementedCourierRouteCommunicateServer) CourierRouteListAll(context.Context, *CourieRouteAllRequest) (*CourierRouteAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CourierRouteListAll not implemented")
}
func (*UnimplementedCourierRouteCommunicateServer) CreateCorrierRoute(context.Context, *CreateCourierRoutesRequest) (*CreateCourierRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCorrierRoute not implemented")
}
func (*UnimplementedCourierRouteCommunicateServer) CourierRouteListOne(context.Context, *CourierRouteListOneRequest) (*CourierRouteListOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CourierRouteListOne not implemented")
}
func (*UnimplementedCourierRouteCommunicateServer) DeleteCourierRouteById(context.Context, *DeleteCourierRouteRequest) (*DeleteCourierRouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCourierRouteById not implemented")
}

func RegisterCourierRouteCommunicateServer(s *grpc.Server, srv CourierRouteCommunicateServer) {
	s.RegisterService(&_CourierRouteCommunicate_serviceDesc, srv)
}

func _CourierRouteCommunicate_CourierRouteListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourieRouteAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierRouteCommunicateServer).CourierRouteListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierRouteCommunicate/CourierRouteListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierRouteCommunicateServer).CourierRouteListAll(ctx, req.(*CourieRouteAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierRouteCommunicate_CreateCorrierRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourierRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierRouteCommunicateServer).CreateCorrierRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierRouteCommunicate/CreateCorrierRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierRouteCommunicateServer).CreateCorrierRoute(ctx, req.(*CreateCourierRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierRouteCommunicate_CourierRouteListOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourierRouteListOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierRouteCommunicateServer).CourierRouteListOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierRouteCommunicate/CourierRouteListOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierRouteCommunicateServer).CourierRouteListOne(ctx, req.(*CourierRouteListOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierRouteCommunicate_DeleteCourierRouteById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCourierRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierRouteCommunicateServer).DeleteCourierRouteById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CourierRouteCommunicate/DeleteCourierRouteById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierRouteCommunicateServer).DeleteCourierRouteById(ctx, req.(*DeleteCourierRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CourierRouteCommunicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CourierRouteCommunicate",
	HandlerType: (*CourierRouteCommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CourierRouteListAll",
			Handler:    _CourierRouteCommunicate_CourierRouteListAll_Handler,
		},
		{
			MethodName: "CreateCorrierRoute",
			Handler:    _CourierRouteCommunicate_CreateCorrierRoute_Handler,
		},
		{
			MethodName: "CourierRouteListOne",
			Handler:    _CourierRouteCommunicate_CourierRouteListOne_Handler,
		},
		{
			MethodName: "DeleteCourierRouteById",
			Handler:    _CourierRouteCommunicate_DeleteCourierRouteById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicate/courierRoutes.proto",
}
