// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: communicate/deposit.proto

package communicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateDepositByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdClient int64 `protobuf:"varint,1,opt,name=idClient,proto3" json:"idClient,omitempty"`
}

func (x *ValidateDepositByIdRequest) Reset() {
	*x = ValidateDepositByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDepositByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDepositByIdRequest) ProtoMessage() {}

func (x *ValidateDepositByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDepositByIdRequest.ProtoReflect.Descriptor instead.
func (*ValidateDepositByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateDepositByIdRequest) GetIdClient() int64 {
	if x != nil {
		return x.IdClient
	}
	return 0
}

type ValidateDepositByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidateDepositByIdResponse) Reset() {
	*x = ValidateDepositByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDepositByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDepositByIdResponse) ProtoMessage() {}

func (x *ValidateDepositByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDepositByIdResponse.ProtoReflect.Descriptor instead.
func (*ValidateDepositByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateDepositByIdResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type Deposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Street   string `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	District string `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	City     string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	State    string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Number   string `protobuf:"bytes,8,opt,name=number,proto3" json:"number,omitempty"`
	Lat      string `protobuf:"bytes,9,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      string `protobuf:"bytes,10,opt,name=lng,proto3" json:"lng,omitempty"`
	ZipCode  string `protobuf:"bytes,11,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	IdCarry  int64  `protobuf:"varint,12,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{2}
}

func (x *Deposit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deposit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deposit) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Deposit) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Deposit) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Deposit) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Deposit) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Deposit) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Deposit) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Deposit) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *Deposit) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Deposit) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type DataDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deposit []*Deposit `protobuf:"bytes,1,rep,name=deposit,proto3" json:"deposit,omitempty"`
}

func (x *DataDeposit) Reset() {
	*x = DataDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeposit) ProtoMessage() {}

func (x *DataDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeposit.ProtoReflect.Descriptor instead.
func (*DataDeposit) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{3}
}

func (x *DataDeposit) GetDeposit() []*Deposit {
	if x != nil {
		return x.Deposit
	}
	return nil
}

type DepositListAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IdCarry int64  `protobuf:"varint,4,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *DepositListAllRequest) Reset() {
	*x = DepositListAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositListAllRequest) ProtoMessage() {}

func (x *DepositListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositListAllRequest.ProtoReflect.Descriptor instead.
func (*DepositListAllRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{4}
}

func (x *DepositListAllRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepositListAllRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DepositListAllRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DepositListAllRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type DepositListAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *DataDeposit `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Page  int64        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64        `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total int64        `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DepositListAllResponse) Reset() {
	*x = DepositListAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositListAllResponse) ProtoMessage() {}

func (x *DepositListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositListAllResponse.ProtoReflect.Descriptor instead.
func (*DepositListAllResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{5}
}

func (x *DepositListAllResponse) GetData() *DataDeposit {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DepositListAllResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DepositListAllResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DepositListAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateDepositRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Street   string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	District string `protobuf:"bytes,3,opt,name=district,proto3" json:"district,omitempty"`
	City     string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country  string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	State    string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Number   string `protobuf:"bytes,7,opt,name=number,proto3" json:"number,omitempty"`
	Lat      string `protobuf:"bytes,8,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      string `protobuf:"bytes,9,opt,name=lng,proto3" json:"lng,omitempty"`
	ZipCode  string `protobuf:"bytes,10,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	IdCarry  int64  `protobuf:"varint,11,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *CreateDepositRequest) Reset() {
	*x = CreateDepositRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositRequest) ProtoMessage() {}

func (x *CreateDepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositRequest.ProtoReflect.Descriptor instead.
func (*CreateDepositRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDepositRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepositRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateDepositRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CreateDepositRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateDepositRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateDepositRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateDepositRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreateDepositRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CreateDepositRequest) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *CreateDepositRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *CreateDepositRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type CreateDepositResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *CreateDepositResponse) Reset() {
	*x = CreateDepositResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositResponse) ProtoMessage() {}

func (x *CreateDepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositResponse.ProtoReflect.Descriptor instead.
func (*CreateDepositResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDepositResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ValidateDepositCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IdCarry int64  `protobuf:"varint,2,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *ValidateDepositCreateRequest) Reset() {
	*x = ValidateDepositCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDepositCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDepositCreateRequest) ProtoMessage() {}

func (x *ValidateDepositCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDepositCreateRequest.ProtoReflect.Descriptor instead.
func (*ValidateDepositCreateRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateDepositCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateDepositCreateRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type ValidateDepositCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *ValidateDepositCreateResponse) Reset() {
	*x = ValidateDepositCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateDepositCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDepositCreateResponse) ProtoMessage() {}

func (x *ValidateDepositCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDepositCreateResponse.ProtoReflect.Descriptor instead.
func (*ValidateDepositCreateResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateDepositCreateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type DeleteDepositByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDepositByIdRequest) Reset() {
	*x = DeleteDepositByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDepositByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepositByIdRequest) ProtoMessage() {}

func (x *DeleteDepositByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepositByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepositByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDepositByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDepositByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteDepositByIdResponse) Reset() {
	*x = DeleteDepositByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDepositByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepositByIdResponse) ProtoMessage() {}

func (x *DeleteDepositByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepositByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepositByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDepositByIdResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UpdateDepositByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Street   string `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	District string `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	City     string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	State    string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Number   string `protobuf:"bytes,8,opt,name=number,proto3" json:"number,omitempty"`
	ZipCode  string `protobuf:"bytes,9,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	IdCarry  int64  `protobuf:"varint,10,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *UpdateDepositByIdRequest) Reset() {
	*x = UpdateDepositByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDepositByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepositByIdRequest) ProtoMessage() {}

func (x *UpdateDepositByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepositByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepositByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDepositByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDepositByIdRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *UpdateDepositByIdRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type UpdateDepositByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateDepositByIdResponse) Reset() {
	*x = UpdateDepositByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDepositByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepositByIdResponse) ProtoMessage() {}

func (x *UpdateDepositByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepositByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateDepositByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDepositByIdResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type ListOneDepositByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListOneDepositByIdRequest) Reset() {
	*x = ListOneDepositByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneDepositByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneDepositByIdRequest) ProtoMessage() {}

func (x *ListOneDepositByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneDepositByIdRequest.ProtoReflect.Descriptor instead.
func (*ListOneDepositByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{14}
}

func (x *ListOneDepositByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListOneDepositByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deposit *Deposit `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
}

func (x *ListOneDepositByIdResponse) Reset() {
	*x = ListOneDepositByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_deposit_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneDepositByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneDepositByIdResponse) ProtoMessage() {}

func (x *ListOneDepositByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_deposit_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneDepositByIdResponse.ProtoReflect.Descriptor instead.
func (*ListOneDepositByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_deposit_proto_rawDescGZIP(), []int{15}
}

func (x *ListOneDepositByIdResponse) GetDeposit() *Deposit {
	if x != nil {
		return x.Deposit
	}
	return nil
}

var File_communicate_deposit_proto protoreflect.FileDescriptor

var file_communicate_deposit_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x1a, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x64, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x1b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x95, 0x02, 0x0a, 0x07, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x43, 0x61,
	0x72, 0x72, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72,
	0x72, 0x79, 0x22, 0x31, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x12, 0x22, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x07, 0x64, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x22, 0x6f, 0x0a, 0x15, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69,
	0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x22, 0x7a, 0x0a, 0x16, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x92, 0x02, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6c, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x4c, 0x0a, 0x1c, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x22, 0x35, 0x0a, 0x1d, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22,
	0x2a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x19, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x22, 0x82, 0x02, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x22, 0x35, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2b,
	0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x1a, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x64, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x52, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x32, 0xb5, 0x04,
	0x0a, 0x12, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x12, 0x52, 0x0a, 0x13, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x15,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x14,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communicate_deposit_proto_rawDescOnce sync.Once
	file_communicate_deposit_proto_rawDescData = file_communicate_deposit_proto_rawDesc
)

func file_communicate_deposit_proto_rawDescGZIP() []byte {
	file_communicate_deposit_proto_rawDescOnce.Do(func() {
		file_communicate_deposit_proto_rawDescData = protoimpl.X.CompressGZIP(file_communicate_deposit_proto_rawDescData)
	})
	return file_communicate_deposit_proto_rawDescData
}

var file_communicate_deposit_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_communicate_deposit_proto_goTypes = []interface{}{
	(*ValidateDepositByIdRequest)(nil),    // 0: ValidateDepositByIdRequest
	(*ValidateDepositByIdResponse)(nil),   // 1: ValidateDepositByIdResponse
	(*Deposit)(nil),                       // 2: Deposit
	(*DataDeposit)(nil),                   // 3: DataDeposit
	(*DepositListAllRequest)(nil),         // 4: DepositListAllRequest
	(*DepositListAllResponse)(nil),        // 5: DepositListAllResponse
	(*CreateDepositRequest)(nil),          // 6: CreateDepositRequest
	(*CreateDepositResponse)(nil),         // 7: CreateDepositResponse
	(*ValidateDepositCreateRequest)(nil),  // 8: ValidateDepositCreateRequest
	(*ValidateDepositCreateResponse)(nil), // 9: ValidateDepositCreateResponse
	(*DeleteDepositByIdRequest)(nil),      // 10: DeleteDepositByIdRequest
	(*DeleteDepositByIdResponse)(nil),     // 11: DeleteDepositByIdResponse
	(*UpdateDepositByIdRequest)(nil),      // 12: UpdateDepositByIdRequest
	(*UpdateDepositByIdResponse)(nil),     // 13: UpdateDepositByIdResponse
	(*ListOneDepositByIdRequest)(nil),     // 14: ListOneDepositByIdRequest
	(*ListOneDepositByIdResponse)(nil),    // 15: ListOneDepositByIdResponse
}
var file_communicate_deposit_proto_depIdxs = []int32{
	2,  // 0: DataDeposit.deposit:type_name -> Deposit
	3,  // 1: DepositListAllResponse.data:type_name -> DataDeposit
	2,  // 2: ListOneDepositByIdResponse.deposit:type_name -> Deposit
	0,  // 3: DepositCommunicate.ValidateDepositById:input_type -> ValidateDepositByIdRequest
	4,  // 4: DepositCommunicate.DepositListAll:input_type -> DepositListAllRequest
	6,  // 5: DepositCommunicate.CreateDeposit:input_type -> CreateDepositRequest
	14, // 6: DepositCommunicate.ListOneDepositById:input_type -> ListOneDepositByIdRequest
	12, // 7: DepositCommunicate.UpdateDepositById:input_type -> UpdateDepositByIdRequest
	10, // 8: DepositCommunicate.DeleteDepositById:input_type -> DeleteDepositByIdRequest
	8,  // 9: DepositCommunicate.ValidateDepositExist:input_type -> ValidateDepositCreateRequest
	1,  // 10: DepositCommunicate.ValidateDepositById:output_type -> ValidateDepositByIdResponse
	5,  // 11: DepositCommunicate.DepositListAll:output_type -> DepositListAllResponse
	7,  // 12: DepositCommunicate.CreateDeposit:output_type -> CreateDepositResponse
	15, // 13: DepositCommunicate.ListOneDepositById:output_type -> ListOneDepositByIdResponse
	13, // 14: DepositCommunicate.UpdateDepositById:output_type -> UpdateDepositByIdResponse
	11, // 15: DepositCommunicate.DeleteDepositById:output_type -> DeleteDepositByIdResponse
	9,  // 16: DepositCommunicate.ValidateDepositExist:output_type -> ValidateDepositCreateResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_communicate_deposit_proto_init() }
func file_communicate_deposit_proto_init() {
	if File_communicate_deposit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communicate_deposit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDepositByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDepositByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositListAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositListAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDepositRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDepositResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDepositCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateDepositCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDepositByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDepositByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDepositByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDepositByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneDepositByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_deposit_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneDepositByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communicate_deposit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communicate_deposit_proto_goTypes,
		DependencyIndexes: file_communicate_deposit_proto_depIdxs,
		MessageInfos:      file_communicate_deposit_proto_msgTypes,
	}.Build()
	File_communicate_deposit_proto = out.File
	file_communicate_deposit_proto_rawDesc = nil
	file_communicate_deposit_proto_goTypes = nil
	file_communicate_deposit_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DepositCommunicateClient is the client API for DepositCommunicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DepositCommunicateClient interface {
	ValidateDepositById(ctx context.Context, in *ValidateDepositByIdRequest, opts ...grpc.CallOption) (*ValidateDepositByIdResponse, error)
	DepositListAll(ctx context.Context, in *DepositListAllRequest, opts ...grpc.CallOption) (*DepositListAllResponse, error)
	CreateDeposit(ctx context.Context, in *CreateDepositRequest, opts ...grpc.CallOption) (*CreateDepositResponse, error)
	ListOneDepositById(ctx context.Context, in *ListOneDepositByIdRequest, opts ...grpc.CallOption) (*ListOneDepositByIdResponse, error)
	UpdateDepositById(ctx context.Context, in *UpdateDepositByIdRequest, opts ...grpc.CallOption) (*UpdateDepositByIdResponse, error)
	DeleteDepositById(ctx context.Context, in *DeleteDepositByIdRequest, opts ...grpc.CallOption) (*DeleteDepositByIdResponse, error)
	ValidateDepositExist(ctx context.Context, in *ValidateDepositCreateRequest, opts ...grpc.CallOption) (*ValidateDepositCreateResponse, error)
}

type depositCommunicateClient struct {
	cc grpc.ClientConnInterface
}

func NewDepositCommunicateClient(cc grpc.ClientConnInterface) DepositCommunicateClient {
	return &depositCommunicateClient{cc}
}

func (c *depositCommunicateClient) ValidateDepositById(ctx context.Context, in *ValidateDepositByIdRequest, opts ...grpc.CallOption) (*ValidateDepositByIdResponse, error) {
	out := new(ValidateDepositByIdResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/ValidateDepositById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositCommunicateClient) DepositListAll(ctx context.Context, in *DepositListAllRequest, opts ...grpc.CallOption) (*DepositListAllResponse, error) {
	out := new(DepositListAllResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/DepositListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositCommunicateClient) CreateDeposit(ctx context.Context, in *CreateDepositRequest, opts ...grpc.CallOption) (*CreateDepositResponse, error) {
	out := new(CreateDepositResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/CreateDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositCommunicateClient) ListOneDepositById(ctx context.Context, in *ListOneDepositByIdRequest, opts ...grpc.CallOption) (*ListOneDepositByIdResponse, error) {
	out := new(ListOneDepositByIdResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/ListOneDepositById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositCommunicateClient) UpdateDepositById(ctx context.Context, in *UpdateDepositByIdRequest, opts ...grpc.CallOption) (*UpdateDepositByIdResponse, error) {
	out := new(UpdateDepositByIdResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/UpdateDepositById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositCommunicateClient) DeleteDepositById(ctx context.Context, in *DeleteDepositByIdRequest, opts ...grpc.CallOption) (*DeleteDepositByIdResponse, error) {
	out := new(DeleteDepositByIdResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/DeleteDepositById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *depositCommunicateClient) ValidateDepositExist(ctx context.Context, in *ValidateDepositCreateRequest, opts ...grpc.CallOption) (*ValidateDepositCreateResponse, error) {
	out := new(ValidateDepositCreateResponse)
	err := c.cc.Invoke(ctx, "/DepositCommunicate/ValidateDepositExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DepositCommunicateServer is the server API for DepositCommunicate service.
type DepositCommunicateServer interface {
	ValidateDepositById(context.Context, *ValidateDepositByIdRequest) (*ValidateDepositByIdResponse, error)
	DepositListAll(context.Context, *DepositListAllRequest) (*DepositListAllResponse, error)
	CreateDeposit(context.Context, *CreateDepositRequest) (*CreateDepositResponse, error)
	ListOneDepositById(context.Context, *ListOneDepositByIdRequest) (*ListOneDepositByIdResponse, error)
	UpdateDepositById(context.Context, *UpdateDepositByIdRequest) (*UpdateDepositByIdResponse, error)
	DeleteDepositById(context.Context, *DeleteDepositByIdRequest) (*DeleteDepositByIdResponse, error)
	ValidateDepositExist(context.Context, *ValidateDepositCreateRequest) (*ValidateDepositCreateResponse, error)
}

// UnimplementedDepositCommunicateServer can be embedded to have forward compatible implementations.
type UnimplementedDepositCommunicateServer struct {
}

func (*UnimplementedDepositCommunicateServer) ValidateDepositById(context.Context, *ValidateDepositByIdRequest) (*ValidateDepositByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateDepositById not implemented")
}
func (*UnimplementedDepositCommunicateServer) DepositListAll(context.Context, *DepositListAllRequest) (*DepositListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositListAll not implemented")
}
func (*UnimplementedDepositCommunicateServer) CreateDeposit(context.Context, *CreateDepositRequest) (*CreateDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeposit not implemented")
}
func (*UnimplementedDepositCommunicateServer) ListOneDepositById(context.Context, *ListOneDepositByIdRequest) (*ListOneDepositByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOneDepositById not implemented")
}
func (*UnimplementedDepositCommunicateServer) UpdateDepositById(context.Context, *UpdateDepositByIdRequest) (*UpdateDepositByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDepositById not implemented")
}
func (*UnimplementedDepositCommunicateServer) DeleteDepositById(context.Context, *DeleteDepositByIdRequest) (*DeleteDepositByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDepositById not implemented")
}
func (*UnimplementedDepositCommunicateServer) ValidateDepositExist(context.Context, *ValidateDepositCreateRequest) (*ValidateDepositCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateDepositExist not implemented")
}

func RegisterDepositCommunicateServer(s *grpc.Server, srv DepositCommunicateServer) {
	s.RegisterService(&_DepositCommunicate_serviceDesc, srv)
}

func _DepositCommunicate_ValidateDepositById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDepositByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).ValidateDepositById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/ValidateDepositById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).ValidateDepositById(ctx, req.(*ValidateDepositByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositCommunicate_DepositListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).DepositListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/DepositListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).DepositListAll(ctx, req.(*DepositListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositCommunicate_CreateDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).CreateDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/CreateDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).CreateDeposit(ctx, req.(*CreateDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositCommunicate_ListOneDepositById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOneDepositByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).ListOneDepositById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/ListOneDepositById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).ListOneDepositById(ctx, req.(*ListOneDepositByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositCommunicate_UpdateDepositById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepositByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).UpdateDepositById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/UpdateDepositById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).UpdateDepositById(ctx, req.(*UpdateDepositByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositCommunicate_DeleteDepositById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDepositByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).DeleteDepositById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/DeleteDepositById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).DeleteDepositById(ctx, req.(*DeleteDepositByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DepositCommunicate_ValidateDepositExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDepositCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DepositCommunicateServer).ValidateDepositExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DepositCommunicate/ValidateDepositExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DepositCommunicateServer).ValidateDepositExist(ctx, req.(*ValidateDepositCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DepositCommunicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DepositCommunicate",
	HandlerType: (*DepositCommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateDepositById",
			Handler:    _DepositCommunicate_ValidateDepositById_Handler,
		},
		{
			MethodName: "DepositListAll",
			Handler:    _DepositCommunicate_DepositListAll_Handler,
		},
		{
			MethodName: "CreateDeposit",
			Handler:    _DepositCommunicate_CreateDeposit_Handler,
		},
		{
			MethodName: "ListOneDepositById",
			Handler:    _DepositCommunicate_ListOneDepositById_Handler,
		},
		{
			MethodName: "UpdateDepositById",
			Handler:    _DepositCommunicate_UpdateDepositById_Handler,
		},
		{
			MethodName: "DeleteDepositById",
			Handler:    _DepositCommunicate_DeleteDepositById_Handler,
		},
		{
			MethodName: "ValidateDepositExist",
			Handler:    _DepositCommunicate_ValidateDepositExist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicate/deposit.proto",
}
