// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: communicate/truck.proto

package communicate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Truck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand   string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model   string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year    string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Plate   string `protobuf:"bytes,5,opt,name=plate,proto3" json:"plate,omitempty"`
	IdCarry int64  `protobuf:"varint,6,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *Truck) Reset() {
	*x = Truck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Truck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Truck) ProtoMessage() {}

func (x *Truck) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Truck.ProtoReflect.Descriptor instead.
func (*Truck) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{0}
}

func (x *Truck) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Truck) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Truck) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Truck) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Truck) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *Truck) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type DataTruck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truck []*Truck `protobuf:"bytes,1,rep,name=truck,proto3" json:"truck,omitempty"`
}

func (x *DataTruck) Reset() {
	*x = DataTruck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTruck) ProtoMessage() {}

func (x *DataTruck) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTruck.ProtoReflect.Descriptor instead.
func (*DataTruck) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{1}
}

func (x *DataTruck) GetTruck() []*Truck {
	if x != nil {
		return x.Truck
	}
	return nil
}

type TruckListAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	IdCarry int64  `protobuf:"varint,3,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
	Plate   string `protobuf:"bytes,4,opt,name=plate,proto3" json:"plate,omitempty"`
}

func (x *TruckListAllRequest) Reset() {
	*x = TruckListAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TruckListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckListAllRequest) ProtoMessage() {}

func (x *TruckListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckListAllRequest.ProtoReflect.Descriptor instead.
func (*TruckListAllRequest) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{2}
}

func (x *TruckListAllRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TruckListAllRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TruckListAllRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

func (x *TruckListAllRequest) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

type TruckListAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *DataTruck `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Page  int64      `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit int64      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Total int64      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *TruckListAllResponse) Reset() {
	*x = TruckListAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TruckListAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruckListAllResponse) ProtoMessage() {}

func (x *TruckListAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruckListAllResponse.ProtoReflect.Descriptor instead.
func (*TruckListAllResponse) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{3}
}

func (x *TruckListAllResponse) GetData() *DataTruck {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TruckListAllResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TruckListAllResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TruckListAllResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateTruckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand   string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model   string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year    string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Plate   string `protobuf:"bytes,4,opt,name=plate,proto3" json:"plate,omitempty"`
	IdCarry int64  `protobuf:"varint,5,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *CreateTruckRequest) Reset() {
	*x = CreateTruckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTruckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTruckRequest) ProtoMessage() {}

func (x *CreateTruckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTruckRequest.ProtoReflect.Descriptor instead.
func (*CreateTruckRequest) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTruckRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateTruckRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateTruckRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CreateTruckRequest) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *CreateTruckRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type CreateTruckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *CreateTruckResponse) Reset() {
	*x = CreateTruckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTruckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTruckResponse) ProtoMessage() {}

func (x *CreateTruckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTruckResponse.ProtoReflect.Descriptor instead.
func (*CreateTruckResponse) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTruckResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type DeleteTruckByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTruckByIdRequest) Reset() {
	*x = DeleteTruckByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTruckByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTruckByIdRequest) ProtoMessage() {}

func (x *DeleteTruckByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTruckByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteTruckByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTruckByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTruckByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *DeleteTruckByIdResponse) Reset() {
	*x = DeleteTruckByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTruckByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTruckByIdResponse) ProtoMessage() {}

func (x *DeleteTruckByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTruckByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteTruckByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTruckByIdResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UpdateTruckByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand   string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model   string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year    string `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	Plate   string `protobuf:"bytes,5,opt,name=plate,proto3" json:"plate,omitempty"`
	IdCarry int64  `protobuf:"varint,6,opt,name=idCarry,proto3" json:"idCarry,omitempty"`
}

func (x *UpdateTruckByIdRequest) Reset() {
	*x = UpdateTruckByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTruckByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTruckByIdRequest) ProtoMessage() {}

func (x *UpdateTruckByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTruckByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdateTruckByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTruckByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTruckByIdRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateTruckByIdRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateTruckByIdRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *UpdateTruckByIdRequest) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *UpdateTruckByIdRequest) GetIdCarry() int64 {
	if x != nil {
		return x.IdCarry
	}
	return 0
}

type UpdateTruckByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateTruckByIdResponse) Reset() {
	*x = UpdateTruckByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTruckByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTruckByIdResponse) ProtoMessage() {}

func (x *UpdateTruckByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTruckByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdateTruckByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTruckByIdResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type ListOneTruckByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ListOneTruckByIdRequest) Reset() {
	*x = ListOneTruckByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneTruckByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneTruckByIdRequest) ProtoMessage() {}

func (x *ListOneTruckByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneTruckByIdRequest.ProtoReflect.Descriptor instead.
func (*ListOneTruckByIdRequest) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{10}
}

func (x *ListOneTruckByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListOneTruckByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truck *Truck `protobuf:"bytes,1,opt,name=truck,proto3" json:"truck,omitempty"`
}

func (x *ListOneTruckByIdResponse) Reset() {
	*x = ListOneTruckByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_communicate_truck_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOneTruckByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOneTruckByIdResponse) ProtoMessage() {}

func (x *ListOneTruckByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communicate_truck_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOneTruckByIdResponse.ProtoReflect.Descriptor instead.
func (*ListOneTruckByIdResponse) Descriptor() ([]byte, []int) {
	return file_communicate_truck_proto_rawDescGZIP(), []int{11}
}

func (x *ListOneTruckByIdResponse) GetTruck() *Truck {
	if x != nil {
		return x.Truck
	}
	return nil
}

var File_communicate_truck_proto protoreflect.FileDescriptor

var file_communicate_truck_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2f, 0x74, 0x72,
	0x75, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x05, 0x54, 0x72,
	0x75, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x43,
	0x61, 0x72, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x64, 0x43, 0x61,
	0x72, 0x72, 0x79, 0x22, 0x29, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x75, 0x63, 0x6b,
	0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x05, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x22, 0x6f,
	0x0a, 0x13, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22,
	0x76, 0x0a, 0x14, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x75, 0x63,
	0x6b, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x22, 0x2f,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22,
	0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x98,
	0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x69, 0x64, 0x43, 0x61, 0x72, 0x72, 0x79, 0x22, 0x33, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x29,
	0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x18, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x6e, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x05, 0x74, 0x72,
	0x75, 0x63, 0x6b, 0x32, 0xe8, 0x02, 0x0a, 0x10, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x54, 0x72, 0x75, 0x63,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x14, 0x2e, 0x54, 0x72, 0x75, 0x63, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x54, 0x72,
	0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x12, 0x18, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e,
	0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x72, 0x75, 0x63, 0x6b,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e,
	0x5a, 0x0c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_communicate_truck_proto_rawDescOnce sync.Once
	file_communicate_truck_proto_rawDescData = file_communicate_truck_proto_rawDesc
)

func file_communicate_truck_proto_rawDescGZIP() []byte {
	file_communicate_truck_proto_rawDescOnce.Do(func() {
		file_communicate_truck_proto_rawDescData = protoimpl.X.CompressGZIP(file_communicate_truck_proto_rawDescData)
	})
	return file_communicate_truck_proto_rawDescData
}

var file_communicate_truck_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_communicate_truck_proto_goTypes = []interface{}{
	(*Truck)(nil),                    // 0: Truck
	(*DataTruck)(nil),                // 1: DataTruck
	(*TruckListAllRequest)(nil),      // 2: TruckListAllRequest
	(*TruckListAllResponse)(nil),     // 3: TruckListAllResponse
	(*CreateTruckRequest)(nil),       // 4: CreateTruckRequest
	(*CreateTruckResponse)(nil),      // 5: CreateTruckResponse
	(*DeleteTruckByIdRequest)(nil),   // 6: DeleteTruckByIdRequest
	(*DeleteTruckByIdResponse)(nil),  // 7: DeleteTruckByIdResponse
	(*UpdateTruckByIdRequest)(nil),   // 8: UpdateTruckByIdRequest
	(*UpdateTruckByIdResponse)(nil),  // 9: UpdateTruckByIdResponse
	(*ListOneTruckByIdRequest)(nil),  // 10: ListOneTruckByIdRequest
	(*ListOneTruckByIdResponse)(nil), // 11: ListOneTruckByIdResponse
}
var file_communicate_truck_proto_depIdxs = []int32{
	0,  // 0: DataTruck.truck:type_name -> Truck
	1,  // 1: TruckListAllResponse.data:type_name -> DataTruck
	0,  // 2: ListOneTruckByIdResponse.truck:type_name -> Truck
	2,  // 3: TruckCommunicate.TruckListAll:input_type -> TruckListAllRequest
	4,  // 4: TruckCommunicate.CreateTruck:input_type -> CreateTruckRequest
	10, // 5: TruckCommunicate.ListOneTruckById:input_type -> ListOneTruckByIdRequest
	8,  // 6: TruckCommunicate.UpdateTruckById:input_type -> UpdateTruckByIdRequest
	6,  // 7: TruckCommunicate.DeleteTruckById:input_type -> DeleteTruckByIdRequest
	3,  // 8: TruckCommunicate.TruckListAll:output_type -> TruckListAllResponse
	5,  // 9: TruckCommunicate.CreateTruck:output_type -> CreateTruckResponse
	11, // 10: TruckCommunicate.ListOneTruckById:output_type -> ListOneTruckByIdResponse
	9,  // 11: TruckCommunicate.UpdateTruckById:output_type -> UpdateTruckByIdResponse
	7,  // 12: TruckCommunicate.DeleteTruckById:output_type -> DeleteTruckByIdResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_communicate_truck_proto_init() }
func file_communicate_truck_proto_init() {
	if File_communicate_truck_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_communicate_truck_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Truck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTruck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TruckListAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TruckListAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTruckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTruckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTruckByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTruckByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTruckByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTruckByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneTruckByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_communicate_truck_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOneTruckByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_communicate_truck_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communicate_truck_proto_goTypes,
		DependencyIndexes: file_communicate_truck_proto_depIdxs,
		MessageInfos:      file_communicate_truck_proto_msgTypes,
	}.Build()
	File_communicate_truck_proto = out.File
	file_communicate_truck_proto_rawDesc = nil
	file_communicate_truck_proto_goTypes = nil
	file_communicate_truck_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TruckCommunicateClient is the client API for TruckCommunicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TruckCommunicateClient interface {
	TruckListAll(ctx context.Context, in *TruckListAllRequest, opts ...grpc.CallOption) (*TruckListAllResponse, error)
	CreateTruck(ctx context.Context, in *CreateTruckRequest, opts ...grpc.CallOption) (*CreateTruckResponse, error)
	ListOneTruckById(ctx context.Context, in *ListOneTruckByIdRequest, opts ...grpc.CallOption) (*ListOneTruckByIdResponse, error)
	UpdateTruckById(ctx context.Context, in *UpdateTruckByIdRequest, opts ...grpc.CallOption) (*UpdateTruckByIdResponse, error)
	DeleteTruckById(ctx context.Context, in *DeleteTruckByIdRequest, opts ...grpc.CallOption) (*DeleteTruckByIdResponse, error)
}

type truckCommunicateClient struct {
	cc grpc.ClientConnInterface
}

func NewTruckCommunicateClient(cc grpc.ClientConnInterface) TruckCommunicateClient {
	return &truckCommunicateClient{cc}
}

func (c *truckCommunicateClient) TruckListAll(ctx context.Context, in *TruckListAllRequest, opts ...grpc.CallOption) (*TruckListAllResponse, error) {
	out := new(TruckListAllResponse)
	err := c.cc.Invoke(ctx, "/TruckCommunicate/TruckListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckCommunicateClient) CreateTruck(ctx context.Context, in *CreateTruckRequest, opts ...grpc.CallOption) (*CreateTruckResponse, error) {
	out := new(CreateTruckResponse)
	err := c.cc.Invoke(ctx, "/TruckCommunicate/CreateTruck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckCommunicateClient) ListOneTruckById(ctx context.Context, in *ListOneTruckByIdRequest, opts ...grpc.CallOption) (*ListOneTruckByIdResponse, error) {
	out := new(ListOneTruckByIdResponse)
	err := c.cc.Invoke(ctx, "/TruckCommunicate/ListOneTruckById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckCommunicateClient) UpdateTruckById(ctx context.Context, in *UpdateTruckByIdRequest, opts ...grpc.CallOption) (*UpdateTruckByIdResponse, error) {
	out := new(UpdateTruckByIdResponse)
	err := c.cc.Invoke(ctx, "/TruckCommunicate/UpdateTruckById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *truckCommunicateClient) DeleteTruckById(ctx context.Context, in *DeleteTruckByIdRequest, opts ...grpc.CallOption) (*DeleteTruckByIdResponse, error) {
	out := new(DeleteTruckByIdResponse)
	err := c.cc.Invoke(ctx, "/TruckCommunicate/DeleteTruckById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TruckCommunicateServer is the server API for TruckCommunicate service.
type TruckCommunicateServer interface {
	TruckListAll(context.Context, *TruckListAllRequest) (*TruckListAllResponse, error)
	CreateTruck(context.Context, *CreateTruckRequest) (*CreateTruckResponse, error)
	ListOneTruckById(context.Context, *ListOneTruckByIdRequest) (*ListOneTruckByIdResponse, error)
	UpdateTruckById(context.Context, *UpdateTruckByIdRequest) (*UpdateTruckByIdResponse, error)
	DeleteTruckById(context.Context, *DeleteTruckByIdRequest) (*DeleteTruckByIdResponse, error)
}

// UnimplementedTruckCommunicateServer can be embedded to have forward compatible implementations.
type UnimplementedTruckCommunicateServer struct {
}

func (*UnimplementedTruckCommunicateServer) TruckListAll(context.Context, *TruckListAllRequest) (*TruckListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TruckListAll not implemented")
}
func (*UnimplementedTruckCommunicateServer) CreateTruck(context.Context, *CreateTruckRequest) (*CreateTruckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTruck not implemented")
}
func (*UnimplementedTruckCommunicateServer) ListOneTruckById(context.Context, *ListOneTruckByIdRequest) (*ListOneTruckByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOneTruckById not implemented")
}
func (*UnimplementedTruckCommunicateServer) UpdateTruckById(context.Context, *UpdateTruckByIdRequest) (*UpdateTruckByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTruckById not implemented")
}
func (*UnimplementedTruckCommunicateServer) DeleteTruckById(context.Context, *DeleteTruckByIdRequest) (*DeleteTruckByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTruckById not implemented")
}

func RegisterTruckCommunicateServer(s *grpc.Server, srv TruckCommunicateServer) {
	s.RegisterService(&_TruckCommunicate_serviceDesc, srv)
}

func _TruckCommunicate_TruckListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruckListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckCommunicateServer).TruckListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TruckCommunicate/TruckListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckCommunicateServer).TruckListAll(ctx, req.(*TruckListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckCommunicate_CreateTruck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTruckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckCommunicateServer).CreateTruck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TruckCommunicate/CreateTruck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckCommunicateServer).CreateTruck(ctx, req.(*CreateTruckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckCommunicate_ListOneTruckById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOneTruckByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckCommunicateServer).ListOneTruckById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TruckCommunicate/ListOneTruckById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckCommunicateServer).ListOneTruckById(ctx, req.(*ListOneTruckByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckCommunicate_UpdateTruckById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTruckByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckCommunicateServer).UpdateTruckById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TruckCommunicate/UpdateTruckById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckCommunicateServer).UpdateTruckById(ctx, req.(*UpdateTruckByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TruckCommunicate_DeleteTruckById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTruckByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TruckCommunicateServer).DeleteTruckById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TruckCommunicate/DeleteTruckById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TruckCommunicateServer).DeleteTruckById(ctx, req.(*DeleteTruckByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TruckCommunicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TruckCommunicate",
	HandlerType: (*TruckCommunicateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TruckListAll",
			Handler:    _TruckCommunicate_TruckListAll_Handler,
		},
		{
			MethodName: "CreateTruck",
			Handler:    _TruckCommunicate_CreateTruck_Handler,
		},
		{
			MethodName: "ListOneTruckById",
			Handler:    _TruckCommunicate_ListOneTruckById_Handler,
		},
		{
			MethodName: "UpdateTruckById",
			Handler:    _TruckCommunicate_UpdateTruckById_Handler,
		},
		{
			MethodName: "DeleteTruckById",
			Handler:    _TruckCommunicate_DeleteTruckById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "communicate/truck.proto",
}
